import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/index.scss";
import Footer from "./components/containers/footer/footer";
import { Header } from "./components/containers/header/Header";
import "normalize.css/normalize.css";
import "swiper/scss";
import Portal from "./components/containers/Portal/Portal";

const montserrat = Montserrat({
  weight: ["400", "500", "600"],
  style: "normal",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Hope Oasis",
  description: "Generated by HopeOasis team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
