import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";

const montserrat = Montserrat({ weight: ['400', '500', '600'], style: 'normal', subsets: ['cyrillic'], });

export const metadata: Metadata = {
  title: "Hoppy Oasis",
  description: "Generated by HopeOasis team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
